# yaml for acr build and push 

trigger:
  - master

pool:
  name: hostedpool
  demands:
  - agent.name -equals   javaagent1

stages:
  - stage: docker_build
    jobs:
      - job: "docker_build"
        steps:
        - task: Maven@4
          inputs:
            mavenPomFile: 'Boardgame/pom.xml'
            goals: 'compile'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
